using System.Collections.Generic;

namespace HCW.AutoCAD.Plugin
{
    /// <summary>
    /// hcwCAD-KIT layer tables and the 29 room-type names.
    /// </summary>
    public static class LayerData
    {
        /// <summary>BPLT (Building Permission Layer Tool): name, ACI colour, linetype, lineweight (0.01mm units, e.g. 50 = 0.50mm).</summary>
        public static readonly (string Name, int Aci, string Linetype, int LwHundredthsMm)[] Bplt =
        {
            ("BP-SITE-BOUNDARY", 1, "Continuous", 50),
            ("BP-SITE-SETBACK", 3, "DASHED2", 25),
            ("BP-SITE-SURRENDER", 3, "DASHED", 18),
            ("BP-ROAD-EDGE", 8, "Continuous", 35),
            ("BP-ROAD-CL", 8, "CENTER2", 18),
            ("BP-DRIVEWAY", 52, "Continuous", 25),
            ("BP-COMP-WALL", 9, "Continuous", 18),
            ("BP-BUILDING-CUT", 7, "Continuous", 50),
            ("BP-BUILDING-VIEW", 7, "Continuous", 25),
            ("BP-DOOR", 252, "Continuous", 18),
            ("BP-WINDOW", 252, "Continuous", 13),
            ("BP-STAIR", 142, "Continuous", 25),
            ("BP-LIFT", 141, "Continuous", 18),
            ("BP-RAMP", 140, "Continuous", 18),
            ("BP-ROOM", 153, "Continuous", 18),
            ("BP-BALCONY", 144, "Continuous", 18),
            ("BP-TERRACE", 96, "Continuous", 18),
            ("BP-PORCH", 22, "Continuous", 18),
            ("BP-LOFT", 33, "DASHED", 13),
            ("BP-MEZZANINE", 33, "Continuous", 18),
            ("BP-SHAFT", 132, "Continuous", 18),
            ("BP-OPEN-SPACE", 3, "Continuous", 18),
            ("BP-PARKING", 151, "Continuous", 18),
            ("BP-PARKING-AISLE", 151, "DASHED", 13),
            ("BP-RWH", 133, "Continuous", 18),
            ("BP-SERVICES", 134, "Continuous", 13),
            ("BP-FIRE", 1, "DASHED", 25),
            ("BP-LEVEL", 6, "Continuous", 13),
            ("BP-PLANTATION", 62, "Continuous", 13),
            ("BP-GARAGE", 152, "Continuous", 18),
            ("BP-ACCESSORY", 152, "Continuous", 13),
            ("BP-PwD", 94, "Continuous", 13),
            ("BP-FAR", 6, "Continuous", 13),
            ("BP-SURVEY-SKETCH", 9, "Continuous", 13),
            ("BP-SECTION", 30, "Continuous", 35),
            ("BP-ELEVATION", 30, "Continuous", 25),
            ("BP-STRUC-REF", 3, "Continuous", 13),
            ("BP-EXISTING", 251, "Continuous", 13),
            ("BP-DEMOLISH", 251, "DASHED", 13),
        };

        /// <summary>HCW Layer Standard v4.0: name, ACI colour, linetype, lineweight (mm), description.</summary>
        public static readonly (string Name, int Aci, string Linetype, double LwMm, string Description)[] Hcw =
        {
            ("AN-REF", 250, "Continuous", 0.09, "Construction lines / viewport borders"),
            ("AN-GRID", 8, "CENTER2", 0.13, "Grid and centre lines"),
            ("AN-SYMB", 7, "Continuous", 0.18, "North point / symbols / logos"),
            ("AN-TEXT", 7, "Continuous", 0.18, "All text - general, title block, keynotes"),
            ("AN-DIMS", 8, "Continuous", 0.18, "Dimensions and leaders"),
            ("AN-HATCH", 9, "Continuous", 0.10, "Hatching and fill patterns"),
            ("A-WALL", 1, "Continuous", 0.35, "Walls - new and existing (cut)"),
            ("A-DEMO", 1, "DASHED2", 0.25, "Elements to be demolished"),
            ("A-COL", 1, "Continuous", 0.35, "Columns (cut)"),
            ("A-DOOR", 2, "Continuous", 0.25, "Doors - frame and swing arc"),
            ("A-WIND", 4, "Continuous", 0.25, "Windows - frame and sill"),
            ("A-GLAZ", 4, "HIDDEN", 0.18, "Glazing / glass line"),
            ("A-STAIR", 2, "Continuous", 0.25, "Stairs - treads, stringers, ramps"),
            ("A-RAIL", 6, "Continuous", 0.20, "Handrails and balustrades"),
            ("A-ROOF", 1, "Continuous", 0.25, "Roof outline and edge"),
            ("A-FLR", 3, "Continuous", 0.18, "Floor finish / slab outline"),
            ("A-CLNG", 3, "Continuous", 0.18, "Ceiling outline and features"),
            ("A-DETAIL", 1, "Continuous", 0.25, "Detail bubbles and reference marks"),
            ("I-FURN", 3, "Continuous", 0.20, "Loose furniture"),
            ("I-JOIN", 5, "Continuous", 0.20, "Fixed joinery - kitchen, wardrobes, built-ins"),
            ("I-FINISH", 30, "Continuous", 0.18, "Finish zones and material areas"),
            ("I-DECOR", 140, "Continuous", 0.15, "Decorative and soft furnishing elements"),
            ("E-CEIL", 6, "Continuous", 0.18, "Ceiling fittings - lights, fans, AC, sensors"),
            ("E-POINT", 2, "Continuous", 0.18, "Wall points - power, data, switches, GPOs"),
            ("E-WIRE", 30, "Continuous", 0.15, "Wiring runs and conduit schematic"),
            ("P-FIXT", 6, "Continuous", 0.18, "Plumbing fixtures - basin, WC, shower, bath"),
            ("P-PIPE", 4, "Continuous", 0.18, "Pipes - supply, drain and vent"),
            ("S-BOUND", 1, "PHANTOM2", 0.35, "Site and property boundary"),
            ("S-ROAD", 8, "Continuous", 0.25, "Road edge and carriageway"),
            ("S-LAND", 3, "Continuous", 0.18, "Landscaping and planting"),
            ("S-TREE", 140, "Continuous", 0.18, "Trees - canopy and trunk"),
            ("S-LEVEL", 2, "Continuous", 0.18, "Spot levels and contours"),
            ("S-DRAIN", 4, "Continuous", 0.18, "Site drainage and channels"),
            ("S-FENCE", 8, "Continuous", 0.20, "Fences and boundary walls"),
            ("PR-TONE", 9, "Continuous", 0.10, "Presentation tone - shadow, fill, material"),
            ("PR-CLOUD", 2, "Continuous", 0.25, "Revision clouds"),
        };

        /// <summary>VHLAYERS (legacy/alternate underscore-style standard): name, ACI colour, linetype, lineweight (mm), plottable.</summary>
        public static readonly (string Name, int Aci, string Linetype, double LwMm, bool Plot)[] Vh =
        {
            ("A_WALL_CUT", 7, "Continuous", 0.50, true),
            ("A_WALL_LOW", 8, "Continuous", 0.25, true),
            ("A_WALL_EXIST", 9, "Continuous", 0.18, true),
            ("A_WALL_DEMO", 1, "DASHED", 0.18, true),
            ("A_WALL_BEYOND", 8, "HIDDEN", 0.13, true),
            ("A_DOOR", 3, "Continuous", 0.25, true),
            ("A_WINDOW", 4, "Continuous", 0.18, true),
            ("A_GLASS", 151, "Continuous", 0.13, true),
            ("A_STAIRS", 2, "Continuous", 0.25, true),
            ("A_RAILING", 8, "Continuous", 0.18, true),
            ("A_FLOOR_PATTERN", 254, "Continuous", 0.09, true),
            ("A_CEILING", 253, "Continuous", 0.09, true),
            ("A_FURNITURE", 30, "Continuous", 0.13, true),
            ("A_JOINERY", 32, "Continuous", 0.18, true),
            ("A_SANITARY", 140, "Continuous", 0.18, true),
            ("A_HATCH_CUT", 250, "Continuous", 0.09, true),
            ("A_HATCH_SURFACE", 253, "Continuous", 0.05, true),
            ("A_SITE", 7, "Continuous", 0.35, true),
            ("A_SETBACK", 1, "DASHED", 0.13, true),
            ("A_PARKING", 6, "Continuous", 0.18, true),
            ("A_LANDSCAPE", 94, "Continuous", 0.13, true),
            ("A_VAASTU", 210, "DASHED", 0.09, true),
            ("A_FSI_FAR", 5, "Continuous", 0.13, true),
            ("A_RAINWATER", 150, "Continuous", 0.18, true),
            ("A_SEPTIC_STP", 145, "Continuous", 0.18, true),
            ("A_SUMP_OHT", 141, "Continuous", 0.18, true),
            ("A_SERVICES_SHAFT", 6, "Continuous", 0.18, true),
            ("A_SECURITY", 1, "Continuous", 0.18, true),
            ("A_SIGNAGE", 30, "Continuous", 0.18, true),
            ("S_COLUMN", 7, "Continuous", 0.50, true),
            ("S_BEAM", 8, "Continuous", 0.35, true),
            ("S_SLAB", 9, "Continuous", 0.25, true),
            ("S_FOOTING", 30, "Continuous", 0.35, true),
            ("S_REBAR", 1, "Continuous", 0.18, true),
            ("S_GRID", 2, "CENTER", 0.13, true),
            ("S_LEVEL", 6, "Continuous", 0.13, true),
            ("E_LIGHT", 2, "Continuous", 0.18, true),
            ("E_SWITCH", 40, "Continuous", 0.13, true),
            ("E_POWER", 30, "Continuous", 0.18, true),
            ("E_CONDUIT", 2, "DASHED", 0.13, true),
            ("P_WATER_SUPPLY", 5, "Continuous", 0.18, true),
            ("P_DRAINAGE", 4, "DASHED", 0.18, true),
            ("P_FIXTURE", 140, "Continuous", 0.18, true),
            ("F_FIRE", 1, "Continuous", 0.25, true),
            ("H_HVAC", 151, "Continuous", 0.18, true),
            ("H_DRAIN", 5, "DASHED", 0.13, true),
            ("AN_DIM", 7, "Continuous", 0.13, true),
            ("AN_TEXT", 7, "Continuous", 0.13, true),
            ("AN_ROOM_NAME", 7, "Continuous", 0.18, true),
            ("AN_LEVEL", 6, "Continuous", 0.13, true),
            ("AN_TAG_DOOR", 3, "Continuous", 0.13, true),
            ("AN_TAG_WINDOW", 4, "Continuous", 0.13, true),
            ("AN_GRID", 2, "Continuous", 0.13, true),
            ("AN_REVISION", 1, "Continuous", 0.18, true),
            ("AN_AREA", 5, "Continuous", 0.13, true),
            ("AN_TITLE", 7, "Continuous", 0.25, true),
            ("P_SHADOW", 251, "Continuous", 0.05, true),
            ("P_POCHE", 252, "Continuous", 0.09, true),
            ("P_CONTEXT", 253, "Continuous", 0.05, true),
            ("P_TREE", 94, "Continuous", 0.09, true),
            ("P_PEOPLE", 252, "Continuous", 0.09, true),
            ("P_CAR", 252, "Continuous", 0.09, true),
            ("P_TEXTURE", 253, "Continuous", 0.05, true),
            ("P_SCREEN", 254, "Continuous", 0.05, true),
            ("A_DETAIL_2D", 7, "Continuous", 0.18, true),
            ("A_DETAIL_3D", 8, "Continuous", 0.13, true),
            ("A_WATERPROOF", 5, "Continuous", 0.18, true),
            ("A_FINISH", 30, "Continuous", 0.13, true),
            ("A_EXPANDED", 6, "Continuous", 0.13, true),
            ("X_GUIDE", 8, "Continuous", 0.05, false),
            ("X_REFERENCE", 9, "Continuous", 0.05, false),
            ("X_TRACE", 251, "Continuous", 0.05, false),
            ("X_RENDER", 253, "Continuous", 0.05, false),
            ("X_COORDINATION", 1, "Continuous", 0.13, false),
            ("X_CHECK", 1, "DASHED", 0.13, false),
        };

        /// <summary>Room-tag tool: two-letter code -> room type label (used by MROOM/FROOM/IROOM and by the generated M/F/I per-type commands).</summary>
        public static readonly (string Code, string RoomType)[] RoomTypes =
        {
            ("br", "Bedroom"),
            ("di", "Dining Room"),
            ("ki", "Kitchen"),
            ("li", "Living Room"),
            ("ba", "Bathroom"),
            ("at", "Attached Toilet"),
            ("ct", "Common Toilet"),
            ("mb", "Master Bedroom"),
            ("st", "Study Room"),
            ("sr", "Store Room"),
            ("pr", "Pooja Room"),
            ("bc", "Balcony"),
            ("te", "Terrace"),
            ("sc", "Staircase"),
            ("co", "Corridor"),
            ("en", "Entrance"),
            ("ut", "Utility"),
            ("ga", "Garage"),
            ("gd", "Garden"),
            ("cy", "Courtyard"),
            ("lo", "Lobby"),
            ("of", "Office"),
            ("gr", "Guest Room"),
            ("pa", "Pantry"),
            ("la", "Laundry"),
            ("wr", "Wardrobe"),
            ("dr", "Dressing Room"),
            ("ht", "Home Theater"),
            ("gy", "Gym"),
        };
    }
}
